### PR TITLE
Bump the versions of the dependencies

### LINKED ISSUE #4: Fix error importing package
If I try to import the package using:

```typescript
const { wren } = await import('@exercism/codemirror-lang-wren')
```

I get the following error:

```
TS2307: Cannot find module '@exercism/codemirror-lang-wren' or its corresponding type declarations.
```

Changing the dynamic import to a regular one results in the same error:

```typescript
import { wren } from '@exercism/codemirror-lang-wren'
```

Importing a file using `import '@exercism/codemirror-lang-wren/dist/index.es'` _does_ work.

The `node_modules/@exercism/codemirror-lang-wren` directory has the following files:

```
dist/index.cjs
dist/index.es.js
LICENSE
package.json
README.md
```

### LINKED ISSUE #5: Add typings to package
In order for this package to integrate nicely with TypeScript projects, it should provide typings. The typings should look something like this:

```typescript
declare module '@exercism/codemirror-lang-wren' {
  import { StreamParser } from '@codemirror/stream-parser'
  export const wren: StreamParser<unknown>
}
```

### PR DESCRIPTION
**Pull request by SleeplessByte**
image

Fixes #4
Fixes #5 

@joshgoebel this also is a precursor to your #2. Note that whilst in #2 you change *main*, you shouldn't. Can you rebase your #2 on this PR?

Happy to help you with anything else you need.

I've released this as 0.6.0 so that @ErikSchierboom can work.

### CODE REVIEW

**Comment by joshgoebel** [comment]
Well that wasn't much time to review. LOL ;-)

**Comment by SleeplessByte** [comment]
Haha sorry! I'm on Slack btw if ya need me

**Comment by ErikSchierboom** [comment]
image

@SleeplessByte The type of the exported `wren` value should be `StreamParser<unknown>` I think.

**Comment by joshgoebel** [comment]
Are we confusing CodeMirror 5 and 6?  I haven o idea what a StreamParser is... The language support exports 3 things:

- [LanguageSupport](https://codemirror.net/6/docs/ref#language.LanguageSupport)
- [LezerLanguage](https://codemirror.net/6/docs/ref#language.LezerLanguage)
- [Lezer#Parser](https://lezer.codemirror.net/docs/ref/#lezer.Parser)

**Comment by joshgoebel** [comment]
Ah, it's an interface.  I think perhaps you want `wrenLanguage`, not `wren`?

**Comment by joshgoebel** [comment]
We're the same interface as Javascript, etc:

```
case 'javascript':
    case 'typescript':
      const { javascript } = await import('@codemirror/lang-javascript')
      return compartment.of(javascript())
    
```

I think you're trying to add an extra layer that's not necessary?

**Comment by ErikSchierboom** [comment]
@joshgoebel Yep, my mistake!

**Pull request merged**
