### PR TITLE
(chore) bump to CodeMirror 6 release dependencies

### LINKED ISSUE #19: Update to stable CodeMirror 6?
Depending on the old 0.19 versions (and removed libraries like @codemirror/highlight) makes it really hard to use this library in a project using stable CM6 now that it's been released.

https://marijnhaverbeke.nl/blog/codemirror-6.html

### PR DESCRIPTION
**Pull request by joshgoebel**
Attempt to resolve #19.

This still doesn't work because it doesn't like `highlightStyle` in extensions, despite this working previously.

Can you help?

### CODE REVIEW

**Comment by joshgoebel** [comment]
@JRaspass  Can you help me figure out why the devtools is broken?

Did they change the default theme between 0.19 and released, do you know?

**Comment by JRaspass** [comment]
Hmm, I might be shooting blind here but in my codebase we have stuff like:
```js
syntaxHighlighting(HighlightStyle.define([
    { color: '#98c379', tag: tags.literal },
    { color: '#e06c75', tag: tags.regexp  },
])
```

Instead of your `tagHighlighter([...])`. With `syntaxHighlighting` and `HighlightStyle` coming from `@codemirror/language`.

And that works fine? I do find the docs a little confusing though, I think they're pretty active on [their forums](https://discuss.codemirror.net) if you get stuck though.

**Comment by joshgoebel** [comment]
`HighlightStyle.define`

That's what I had before, but when I upgraded to `@lezer/highlight` it looked like the API changed, let me take another look... perhaps there are just two very similar and confusing apis... but this method came from `@codemirror/highlight` before, so when I say an identify APi in `@lezer/highlight` I assumed that was the same thing.

**Comment by JRaspass** [comment]
Yeah I think `HighlightStyle` moved from `@codemirror/hightlight` to `@codemirror/language`.

**Comment by joshgoebel** [comment]
Well now that seems to work great... anyway you could test this before I publish?

**Comment by JRaspass** [comment]
Tested and it's working :tada:

image
(looks like range isn't quite right, but that's an issue for later, this at least works with CM6, so thank you!)

I even [shipped](https://github.com/code-golf/code-golf/commit/4f14aeccb14b320d3bc0b045f6387aefe129ca5a) it to live Code Golf if you wanna test it out yourself ;-) https://code.golf/fizz-buzz#wren

**Comment by joshgoebel** [comment]
> looks like range isn't quite right

Yeah, no guarantees it's perfect.  PRs welcome. :-)

**Comment by joshgoebel** [comment]
Any thoughts on the correct version pinning?

**Comment by SleeplessByte** [comment]
What is it exactly that I can help with :) ?

**Comment by joshgoebel** [comment]
Best practices on npm version pinning... if we want to say "entire 6.x series", is this the best way:

```
    "@codemirror/autocomplete": "^6.0.0",
     "@codemirror/language": "^6.0.0",
```

**Comment by dem4ron** [comment]
Hey! 
Exercism is moving to CodeMirror 6 `^6.0.0`. 
This is one of the two packages that needs to be republished with later dependencies. Basically what you already have here. :) Could you please help with that?

Thanks!

**Pull request merged**
